# Configuration for the BMAD Algorithm Output Regression Testing Expansion Pack

# Local path to the folder containing algorithm outputs to be tested.
# This should be an absolute path on your local machine.
algorithm_outputs_path: "/path/to/your/algorithm/outputs"

# Configuration for algorithm output testing
testing:
  parallel: true
  fail-fast: true
  output_file_types: [".csv", ".json", ".txt", ".xlsx", ".tsv"]
  validation_methods: ["schema", "data_quality", "regression", "performance"]
