# Configuration for the BMAD Algorithm Output Regression Testing Expansion Pack

# Local path to the folder containing algorithm outputs to be tested.
# This should be an absolute path on your local machine.
algorithm_outputs_path: "/Users/aryatupkary/Desktop/outputs"

# Configuration for algorithm output testing
testing:
  parallel: true
  fail-fast: true
  output_file_types: [".csv", ".json", ".txt", ".xlsx", ".tsv"]
  validation_methods: ["schema", "data_quality", "regression", "performance"]

# HTML Report Configuration
html_report:
  enabled: true
  output_file: "algorithm-validation-report.html"
  output_dir: "./reports"  # Directory to save HTML reports
  include_charts: true
  include_interactive_filters: true
  embed_data: true  # Create self-contained HTML file
  theme: "default"  # Options: default, dark, light

# MCP Excel Server Configuration for accelerated TSV/Excel parsing
mcp_excel_server:
  enabled: true
  command: "uvx"
  args: ["mcp-excel-server"]
  env:
    PYTHONPATH: "/usr/local/bin/python3"  # Adjust path as needed for your system
  supported_formats: [".xlsx", ".xls", ".csv", ".tsv", ".json"]
  performance_mode: true  # Enable performance optimizations for large files
  cache_enabled: true  # Cache parsed data for repeated analysis
  max_file_size_mb: 500  # Maximum file size to process (MB)
  parallel_processing: true  # Process multiple files in parallel

# Workflow Configuration
workflow:
  default_scope: "all"  # Default scope for /test-algorithm-outputs
  default_validation: "all"  # Default validation types
  parallel_execution: true  # Run validations in parallel when possible
  fail_fast: false  # Continue with all validations even if some fail
