# VIRAT Transformation System Extension Pack Configuration
name: virat-transformation-system
version: 1.0.0
description: "VIRAT Transformation System for multi-repository development workflows"
author: "BMAD Team"
license: "MIT"

# Repository paths and base branches for the three interconnected repositories
repositories:
  irisx-algo:
    path: "/Users/viratbansal/IdeaProjects/irisx-algo"
    base_branch: "caas-release"
  ms-loadapis-ril-final:
    path: "/Users/viratbansal/IdeaProjects/ms-loadapis-ril-final"
    base_branch: "release-optimised"
  irisx-config:
    path: "/Users/viratbansal/IdeaProjects/irisx-config"
    base_branch: "caas-release-fixed"

# Target completion time in hours
target_completion_time: 2

# Success metrics
success_metrics:
  development_velocity: "2 hours per requirement"
  accuracy: "95%+ success rate"
  coverage: "80% of typical business requirements"
  quality: "Maintain existing code quality standards"
