# BMAD VIRTUAL INTELLIGENT Repository ANALYSIS AND TRANSFORMATION Extension Pack Configuration
name: bmad-virtual-intelligent-repository-analysis-transformation
version: 1.0.0
short-title: VIRAT Repository Intelligence
description: "VIRTUAL INTELLIGENT Repository ANALYSIS AND TRANSFORMATION for multi-repository development workflows"
author: "BMAD Team"
license: "MIT"

# Installation Questions
installation_questions:
  - name: "algoRepoPath"
    type: "input"
    message: "Enter the local path to your Algorithm repository (irisx-algo):"
    default: "../irisx-algo"
    validate: "required"
  - name: "configRepoPath"
    type: "input"
    message: "Enter the local path to your Config repository (irisx-config):"
    default: "../irisx-config"
    validate: "required"
  - name: "loadapisRepoPath"
    type: "input"
    message: "Enter the local path to your LoadAPIs repository (ms-loadapis-ril-final):"
    default: "../ms-loadapis-ril-final"
    validate: "required"

# Repository paths for the three interconnected repositories
# These will be configured during installation via the questions above
repositories:
  irisx-algo: "{ALGO_REPO_PATH}"
  ms-loadapis-ril-final: "{LOADAPIS_REPO_PATH}"
  irisx-config: "{CONFIG_REPO_PATH}"

# Environment-specific base branch configurations
# VIRAT will automatically detect environment from requirement document
environments:
  prod:
    name: "Production"
    base_branches:
      algorithm: "caas-release"
      loadapi: "release_optimised"
      config: "caas-staging_fix"
  
  reliance:
    name: "Reliance"
    base_branches:
      algorithm: "master-ril"
      loadapi: "caas-ril-uploads"
      config: "master-ril"
  
  phoenix:
    name: "Phoenix"
    base_branches:
      algorithm: "master-adidas-reliance-prod"
      loadapi: "caas-phoenix-uploads"
      config: "master-adidas-ril"

# Target completion time in hours
target_completion_time: 2

# Success metrics
success_metrics:
  development_velocity: "2 hours per requirement"
  accuracy: "95%+ success rate"
  coverage: "80% of typical business requirements"
  quality: "Maintain existing code quality standards"
