# BMAD VIRTUAL INTELLIGENT Repository ANALYSIS AND TRANSFORMATION Extension Pack Configuration
name: bmad-virtual-intelligent-repository-analysis-transformation
version: 1.0.0
short-title: VIRAT Repository Intelligence
description: "VIRTUAL INTELLIGENT Repository ANALYSIS AND TRANSFORMATION for multi-repository development workflows"
author: "BMAD Team"
license: "MIT"

# Installation Questions
installation_questions:
  - name: "algoRepoPath"
    type: "input"
    message: "Enter the local path to your Algorithm repository (irisx-algo):"
    default: "../irisx-algo"
    validate: "required"
  - name: "configRepoPath"
    type: "input"
    message: "Enter the local path to your Config repository (irisx-config):"
    default: "../irisx-config"
    validate: "required"
  - name: "loadapisRepoPath"
    type: "input"
    message: "Enter the local path to your LoadAPIs repository (ms-loadapis-ril-final):"
    default: "../ms-loadapis-ril-final"
    validate: "required"
  - name: "notionApiKey"
    type: "password"
    message: "Enter your Notion API Key (Integration Token) - optional, press Enter to skip:"
    default: ""
    validate: "optional"
    env_var: "NOTION_API_KEY"
  - name: "notionDatabaseId"
    type: "input"
    message: "Enter your Notion Database ID (for requirements) - optional, press Enter to skip:"
    default: ""
    validate: "optional"
    env_var: "NOTION_DATABASE_ID"

# Repository paths for the three interconnected repositories
# These will be configured during installation via the questions above
repositories:
  irisx-algo: "{ALGO_REPO_PATH}"
  ms-loadapis-ril-final: "{LOADAPIS_REPO_PATH}"
  irisx-config: "{CONFIG_REPO_PATH}"

# Environment-specific base branch configurations
# VIRAT will automatically detect environment(s) from requirement document
# Supports multiple environments (comma-separated): processes each sequentially
environments:
  prod:
    name: "Production"
    base_branches:
      algorithm: "caas-release"
      loadapi: "release_optimised"
      config: "caas-staging_fix"
  
  reliance:
    name: "Reliance"
    base_branches:
      algorithm: "master-ril"
      loadapi: "caas-ril-uploads"
      config: "master-ril"
  
  phoenix:
    name: "Phoenix"
    base_branches:
      algorithm: "master-adidas-reliance-prod"
      loadapi: "caas-phoenix-uploads"
      config: "master-adidas-ril"

# Target completion time in hours
target_completion_time: 2

# Notion Integration Configuration (Optional)
notion:
  enabled: "{NOTION_API_KEY_EXISTS}"  # Auto-enabled if NOTION_API_KEY is set
  api_version: "2022-06-28"
  base_url: "https://api.notion.com/v1"
  database_id: "{NOTION_DATABASE_ID}"
  api_key: "{NOTION_API_KEY}"
  field_mappings:
    requirement_id: "No ID"  # Column name in Notion DB (e.g., REQ-994)
    content_section: "Below Comments"  # Extract from page content below Comments
    push_target_section: "Below Comments"  # Push documentation to same location
  documentation_patterns:
    - "*.md"
    - "*-ANALYSIS.md"
    - "*-IMPLEMENTATION.md"
    - "*-PLAN.md"
    - "CHANGELOG.md"

# Success metrics
success_metrics:
  development_velocity: "2 hours per requirement"
  accuracy: "95%+ success rate"
  coverage: "80% of typical business requirements"
  quality: "Maintain existing code quality standards"
  notion_integration: "Seamless extraction and push-back to Notion"
