# BMAD VIRTUAL INTELLIGENT Repository ANALYSIS AND TRANSFORMATION Extension Pack Configuration
name: bmad-virtual-intelligent-repository-analysis-transformation
version: 1.0.0
short-title: VIRAT Repository Intelligence
description: "VIRTUAL INTELLIGENT Repository ANALYSIS AND TRANSFORMATION for multi-repository development workflows"
author: "BMAD Team"
license: "MIT"

# Installation Questions
installation_questions:
  - name: "prdShared"
    type: "confirm"
    message: "Will the PRD (Product Requirements Document) be shared across repositories?"
    default: true
  - name: "repositoryAddresses"
    type: "input"
    message: "Enter the base repository addresses (comma-separated, e.g., github.com/org, gitlab.com/company):"
    default: "github.com/increff"
    validate: "required"
  - name: "multiRepoWorkflow"
    type: "confirm"
    message: "Will you be working with multiple interconnected repositories (Algorithm, LoadAPI, Config)?"
    default: true

# Repository paths for the three interconnected repositories
repositories:
  irisx-algo: "/Users/viratbansal/IdeaProjects/irisx-algo"
  ms-loadapis-ril-final: "/Users/viratbansal/IdeaProjects/ms-loadapis-ril-final"
  irisx-config: "/Users/viratbansal/IdeaProjects/irisx-config"

# Target completion time in hours
target_completion_time: 2

# Success metrics
success_metrics:
  development_velocity: "2 hours per requirement"
  accuracy: "95%+ success rate"
  coverage: "80% of typical business requirements"
  quality: "Maintain existing code quality standards"
