# DEPLOYMENT CREDENTIALS TEMPLATE
# Copy this file to 'deployment-credentials.yaml' and fill in your actual credentials
# NEVER commit the actual deployment-credentials.yaml file!

# Azure Storage Authentication (for JAR, LoadAPI, Config uploads)
azure_storage:
  storage_account: "stincrfmseqc02"
  resource_group: "rg-ms-enterprise-qc-02"
  subscription_id: "21dc781a-7dbc-4b66-b799-2bf24197b807"
  
  # Choose ONE authentication method and fill in the value:
  authentication:
    # Option 1: Storage Account Key (Recommended for automation)
    storage_account_key: "YOUR_STORAGE_ACCOUNT_KEY_HERE"
    
    # Option 2: Connection String
    connection_string: "YOUR_CONNECTION_STRING_HERE"
    
    # Option 3: SAS Token (Time-limited, more secure)
    sas_token: "YOUR_SAS_TOKEN_HERE"
    
    # Option 4: Azure CLI Login (interactive, no stored keys)
    use_cli_login: false  # Set to true if using 'az login'

# QC MySQL Database
mysql_database:
  host: "mysql-manager-qc-02-mse.nextscm.com"
  port: 3306
  username: "nextscm-app-user"
  password: "YOUR_MYSQL_PASSWORD_HERE"  # NEVER commit actual password!
  database: "master"

# Notification Configuration (Optional)
notifications:
  slack:
    webhook_url: "YOUR_SLACK_WEBHOOK_URL_HERE"
    channel: "#qc-deployments"
    enabled: false
  
  email:
    smtp_server: "smtp.example.com"
    smtp_port: 587
    from_email: "deployments@example.com"
    to_emails:
      - "qc-team@example.com"
    smtp_username: "YOUR_SMTP_USERNAME_HERE"
    smtp_password: "YOUR_SMTP_PASSWORD_HERE"
    enabled: false

# Deployment Tracking (Optional)
deployment_tracking:
  log_location: "./deployment-logs"
  keep_backups_days: 30
  backup_location: "./deployment-backups"

# Environment Configuration
environment:
  name: "QC"
  allow_production_deployment: false
  require_approval: false
  auto_notify_qc_team: true

