# BMAD Notion Integration Extension Pack Configuration
name: bmad-notion
version: 1.0.0
short-title: Notion Integration
description: "Seamless Notion integration for requirement extraction and documentation push-back"
author: "BMAD Team"
license: "MIT"

# Default orchestrator - use @notion to activate
default_agent: notion-integrator
orchestrator: "@notion"

# Installation Questions
installation_questions:
  - name: "notionApiKey"
    type: "password"
    message: "Enter your Notion API Key (Integration Token):"
    default: ""
    validate: "required"
    env_var: "NOTION_API_KEY"
  - name: "notionDatabaseId"
    type: "input"
    message: "Enter your Notion Database ID (for requirements):"
    default: ""
    validate: "required"
    env_var: "NOTION_DATABASE_ID"
  - name: "notionViewId"
    type: "input"
    message: "Enter your Notion View ID (optional):"
    default: ""
    validate: "optional"

# Notion API Configuration
notion:
  api_version: "2022-06-28"
  base_url: "https://api.notion.com/v1"
  database_id: "{NOTION_DATABASE_ID}"
  api_key: "{NOTION_API_KEY}"
  view_id: "{NOTION_VIEW_ID}"

# Field Mappings - Map Notion properties to requirement fields
field_mappings:
  # Primary identifier field - used to locate the page
  requirement_id: "No ID"  # Column name in Notion DB (e.g., REQ-994)
  
  # ONLY extract Request Description - nothing else
  request_description: "Request Description"
  
  # Push target section in Notion (where docs will be uploaded)
  push_target_section: "III. DEVELOPMENT"

# Documentation file patterns to push back to Notion
documentation_patterns:
  - "*.md"
  - "*-ANALYSIS.md"
  - "*-IMPLEMENTATION.md"
  - "*-PLAN.md"
  - "CHANGELOG.md"
  - "README*.md"

# Target completion time in hours
target_completion_time: 2

# Success metrics
success_metrics:
  extraction_accuracy: "100% field mapping"
  push_success_rate: "95%+ successful uploads"
  sync_reliability: "Real-time bidirectional sync"

